networks:
  default:
    name: nvidia-rag
services:
  ingest-client:
    build:
      context: ../../
      dockerfile: ./src/ingest_service/Dockerfile
    command: "/bin/sh -c \"python3 import_csv_to_sql.py --host postgres --port 5432\
      \ &&\n            python3 ingest_doc.py --host unstructured-retriever --port\
      \ 8081\"\n"
    container_name: ingest-client
    environment:
    - NVWB_TRIM_PREFIX=true
    image: nvcr.io/nvidia/blueprint/aiva-customer-service-ingest-client:1.1.0
